service: practice-serverless
frameworkVersion: '3'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'VehicleTable'
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:*
          Resource:
            - Fn::GetAtt: [ VehicleTable, Arn ]

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    VehicleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VehicleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH